### PR TITLE
Add DSD sample formats

### PR DESCRIPTION
**Pull request by lintweaker**
This patch adds support for using the ALSA DSD sample formats avaiable in
recents kernel/ALSA versions.

### CODE REVIEW

**Comment by lintweaker** [comment]
It's probably best to put a ALSA version check around the DSD sample formats so it still compiles when people are using older version of ALSA (i.e. ALSA < 1.0.29)

**Comment by lintweaker** [comment]
Okay, I have added a ALSA lib version check.

**Comment by larsimmisch** [comment]
Thanks (didn't see SND_LIB_VERSION, doh). Works for me.

**Comment by lintweaker** [comment]
Thanks!

**Pull request merged**
