### PR TITLE
Add nominal_bits and physical_bits info

### PR DESCRIPTION
**Pull request by viinikv**
Adds the information discussed in pull request #144

Right, I guess this ended up being a new pull request now that the previous one was merged.

(Using ``git diff --color-words=.`` makes the doc/libalsaaudio.rst diff more clear.)

### CODE REVIEW

**Comment by perexg** [comment]
The significant bits are always related to the sample width (bits), so the sample picture should look like:

```
  MSB |0000 XXXX XXXX 0000| LSB
            |-sign.-|
            |---nominal---|
      |-----physical------|
```

Also, I would consider to not use the word "nominal". It's more related to finance in my eyes. Just use bits or sample bits.

**Comment by viinikv** [comment]
@perexg hi, thanks for your response. This is what I get when I run the code:
```
format = 'S24_LE' (Signed 24 bit Little Endian)
significant bits = 32
nominal bits = 24
physical bits = 32
```
Shouldn't I get ``significant bits = 24`` according to your picture? The regular S32_LE format works as expected:
```
format = 'S32_LE' (Signed 32 bit Little Endian)
significant bits = 24
nominal bits = 32
physical bits = 32
```

And about the name "nominal", that's the name [alsa-lib doc uses](https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m___helpers.html#ga8d4e07f2d68cc16f607857ed8a222a29), and at least I prefer a more specific name because it is harder to confuse with the other two.

**Comment by perexg** [comment]
I would probably use just "sample bits", because it's something that the user expects and this bit-width is also in the format name (usually). I eliminated the "nominal" word in alsa-lib doc (see the above reference).

For msbits value - I am trying to fix this in the kernel side - https://lore.kernel.org/linux-sound/20240222173649.1447549-1-perex@perex.cz/ for all formats. Originally, this value was defined mostly for S32_LE,U32_LE (and BE)  formats. I don't think that we need to use the physical sample word for this value, because the starting bit is defined in the format itself.

**Comment by larsimmisch** [comment]
> I would probably use just "sample bits", because it's something that the user expects and this bit-width is also in the format name (usually). I eliminated the "nominal" word in alsa-lib doc (see the above reference).

+1 for consistency with alsa-lib doc

**Comment by viinikv** [comment]
The kernel commit message for ``fb6723d`` by Takashi Sakamoto said:
```
    I note that [S|U]24 formats are used for 'right-justified' 24 bit sample
    formats within 32 bit frame. The first byte in most significant bit
    should be invalidated. Although the msbits exposed to userspace should be
    zero as invalid value, actually it is 32 from physical width of format.
```
I guess that was not an authoritative definition.

I do agree that being consistent with alsa-lib and kernel naming is currently the best option.

@perexg:
1. Do you expect ``snd_pcm_hw_params_get_sbits()`` to be changed in alsa-lib for ``SNDRV_PROTOCOL_VERSION(2, 0, 16)`` and earlier to match the new output?
2. Is the kernel change going to break S24_LE for programs that incorrectly use ``snd_pcm_hw_params_get_sbits()`` instead of ``snd_pcm_format_physical_width()`` like pyalsaaudio until a couple of days ago?

**Comment by perexg** [comment]
> The kernel commit message for `fb6723d` by Takashi Sakamoto said:
> 
> ```
>     I note that [S|U]24 formats are used for 'right-justified' 24 bit sample
>     formats within 32 bit frame. The first byte in most significant bit
>     should be invalidated. Although the msbits exposed to userspace should be
>     zero as invalid value, actually it is 32 from physical width of format.
> ```
> 
> I guess that was not an authoritative definition.

The significant bits may be used for [SU]24 formats, too. For example, DMA controller may transfer all 24 bits, but the codec behind can handle only 20 bits. In this case, it's fine to transfer all usable 24 bits but the driver may pass to the user space only 20 (m)sbits to notify that some bits are ignored.

> I do agree that being consistent with alsa-lib and kernel naming is currently the best option.
> 
> @perexg:
> 
>     1. Do you expect `snd_pcm_hw_params_get_sbits()` to be changed in alsa-lib for `SNDRV_PROTOCOL_VERSION(2, 0, 16)` and earlier to match the new output?

Yes, see the above commit in alsa-lib.

>     2. Is the kernel change going to break S24_LE for programs that incorrectly use `snd_pcm_hw_params_get_sbits()` instead of `snd_pcm_format_physical_width()` like pyalsaaudio until a couple of days ago?

You probably refer eda913b203cf0a2fc55346f12d89a995273ebe43 . This code was broken also for common format S32_LE where some drivers may return value 20 (bits). I don't think that we have other code which is using sbits output in this way.

**Comment by ossilator** [comment]
hi @perexg,
thanks for the clarifications.
but i think you already disproved your "just use sample bits" yourself, by using "usable sample bits" in the adjusted documentation. it's obvious that being more specific is necessary. given that you don't like "nominal" (fair enough), how about using "logical"? that's a rather well-established term in the context of memory addressing. "usable" is too ambiguous, as there is too much semantic overlap with "significant".

**Comment by perexg** [comment]
It's not either logical. After more thinking, it seems the correct word is resolution (sample resolution in bits starting from the first most significant bit defined by the format).

**Comment by ossilator** [comment]
no, that has the same problem as "used" - it sort of suggests that the insignificant bits are not included, even though they actually are.

both "logical" and "nominal" are really just placeholders for something that needs to be defined. their advantage is that they are not misleading, because they don't have an intuitive association in this context.

i haven't yet come up with a term that would fit intuitively.

**Comment by RonaldAJ** [comment]
Isn't it a kind of serialization resolution? The significant bits are related to the original ADC output, the physical to the physical memory used now. Whereas these "nominal" bits are more related to the number of bits used in the serialized transport contexts?

**Comment by perexg** [comment]
@ossilator : I don't get the point. The purpose of this value is to let application know which bits are not used (processed) at some point. So it's the real sample resolution for linear formats.

**Comment by RonaldAJ** [comment]
I think @perexg is redefining "significant bits" to "sample resolution"  whereas @ossilator reads it as a redefinition of "nominal".  

I think the proposed change to the documentation of snd_pcm_hw_params_get_sbits does a good job at explaining the output of that function.

**Comment by ossilator** [comment]
oh, indeed, i overlooked that this actually refers to the significant bits. :innocent:  that's fine then.

but that still leaves us with needing a proper term for the, uhm, "other" bit width.

serialization as such is correct, but i don't see how to turn that into an attribute that would bring clarity - "serialized sample width" doesn't cut it, because actual serialization formats use the physical bit width of the sample format.

**Comment by RonaldAJ** [comment]
Just a few stupid questions for clarification:
@perexg You number the bits from least significant (bit 0)  to most significant (bit physical width)? And when numbered that way the sample starts at position (bit "nominal" width - 1)
and ends at (bit ("nominal" width - 1 - sample resolution )) ? Which makes the "nominal" width a sample start position? Where start means the location of the most significant bit in the sample?

**Comment by perexg** [comment]
The valid sample bits (without padding) are related to the format. See the improved comment in https://github.com/alsa-project/alsa-lib/commit/4489923d2ca2ee776c79454ce352a26b89ecca18 . For example (choosing different format than in example), S20_LE format stores sample bits in low three bytes (padding bits 20-31 in 32-bit word due to hardware capabilities). Hardware or software (whole processing chain including DMA controller and ADC/DAC resolution) may crop this (using only significant bits in this 0-19 bit range). If value 18 is returned, only bits 2-23 are effectively used and the low two bits are ignored).

**Comment by larsimmisch** [comment]
I'm inclined to merge this as is. _nominal_ works for me, I read it as _by name_.

**Comment by perexg** [comment]
My preference is just to keep with "sample width" or "sample bits" based on the format. We probably do not need to find any fancy word to specify this more.

If you merge PR as is, the significant bits are incorrect in doc (position), now.

My preference is:

```
   sample_bits            *used bits in sample* [#tss]_                 integer (negative indicates error)
   resolution_bits        *used significant bits in sample* [#tss]_     integer (negative indicates error)
   physical_bits          *whole sample width in bits* [#tss]_          integer (negative indicates error)
```

**Comment by RonaldAJ** [comment]
"nominal" refers to the width specified by the "format". So an alternative would be to call it the "format_width". The "physical" width is the in memory width, that could be called "(in_)memory_width". That way the names are more descriptive.

**Comment by viinikv** [comment]
I was kind of waiting for new kernel and alsa releases to maybe mention them in the documentation. The commit 85df6b5 "ALSA: pcm: clarify and fix default msbits value for all formats" was included in v6.8-rc7 and therefore in the just released v6.8. 

There appears to be a new function in sound/core/pcm_lib.c called snd_pcm_hw_params_bits() with the documentation:
```
/**
 * snd_pcm_hw_params_bits - Get the number of bits per the sample.
 * @p: hardware parameters
 *
 * Return: The number of bits per sample based on the format,
 * subformat and msbits the specified hw params has.
 */
```
Does anybody want to guess which number this function returns? It's the "nominal bits" or "sample bits" for the regular formats, but "significant bits" or msbits for the new left-aligned subformats like SNDRV_PCM_SUBFORMAT_MSBITS_24. I guess because it's not in the userspace api and currently only used by the hda driver it can say or return whatever.

I wrote a program that tests which bits are set in the samples and:
1. apparently my fix for the buffer size isn't quite correct, as it still crashes when the physical size is not a multiple of 8, which is true for one format (PCM_FORMAT_IMA_ADPCM, .width = 4, .phys = 4). Changing the code to use snd_pcm_format_size(), which is ``samples * phys_width / 8`` needs a bit more care because of how ``self->framesize`` is used in other places. Maybe we can just add something like assert(physical_bits % 8 == 0) to get rid of the segfault.

2. for some reason I'm only getting 20 significant bits even though the hardware manual and alsa say 24. This is weird but probably irrelevant as it seems like a hardware "feature". And as a note, the Allwinner A10 manual I'm currently reading uses "sample bits" to mean "significant bits" or ADC resolution.

The naming question hasn't converged, but it seems that the maintainers of this library are happy with the names as they are.

**Review by larsimmisch — APPROVED** [review]
Great, thank you!

**Comment by viinikv** [comment]
@ossilator done.

**Review by ossilator — APPROVED** [review]

**Pull request merged**
