### PR TITLE
Add timestamp_raw function

### PR DESCRIPTION
**Pull request by RonaldAJ**
For many IoT applications timestamps generated at the acquiring device are required. Currently pyalsaaudio does not support obtaining timestamps from the audio card itself.

However, ALSA contains a function snd_pcm_htimestamp which yields a high resolution timestamp. (Documentation here: https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga3946abd34178b3de60fd5329b71c189b)

This timestamp still needs interpretation therefore I propose to call the pyalsaaudio equivalent "timestamp_raw", so "timestamp" with an added "raw" to stress that the output needs to be interpreted.

The 3 values returned in a tuple are seconds, nanoseconds and the available samples in the buffer at the moment the timestamp was grabbed. If I read the documentation correctly.

### CODE REVIEW

**Review by larsimmisch — APPROVED** [review]
Looks good to me. I would have called the function `alsapcm_timestamp`, though, that's the current convention (prefix the name with `alsapcm_` for PCM methods)

**Comment by RonaldAJ** [comment]
If we follow the convention you provide I get to htimestamp. So I provided a version using that.

**Review by larsimmisch — APPROVED** [review]
Cool, thanks

**Comment by larsimmisch** [comment]
Can you take a look at the conflict? If not, I can probably do it sometime over easter

**Comment by RonaldAJ** [comment]
I guess it is because it was created on  separate branch. I can rebase these changes on the previous ones.

**Comment by RonaldAJ** [comment]
This process this way is a bit new to me. Is it correct now?

**Comment by larsimmisch** [comment]
Yes, the diff looks good.

**Pull request merged**
