### PR TITLE
Prepare 0.11.0

### PR DESCRIPTION
**Pull request by larsimmisch**
Prepare for new release

### CODE REVIEW

**Comment by larsimmisch** [comment]
Tagging, uploading of the documentation are still outstanding. Did I miss contributions?

**Comment by ossilator** [comment]
amended the commit.

i left out the loopback code, as it's still WIP if i gather it correctly. fwiw, consider adding a description to that thing, so one doesn't have to read the code to figure out what it really does.

i took the credits out of the main changelog, as they make it messy, esp. when multiple changes are in one PR. also, the PR numbers aren't all that useful to users, for whom the changelog is.
i'm still not entirely happy with this format. an alternative would be adding a separate AUTHORS.md file which lists the authors with their respective contributions. i actually did that in one of my projects, see https://sourceforge.net/p/isync/isync/ci/master/tree/AUTHORS.

two requests resulting from browsing the history:
- please don't push non-trivial stuff without review, even to the loopback code, as it still makes the overall history messy. n.b., it would have been better to do the loopback work on a branch instead - then you could have massaged the history prior to mainlining.
- when committing changes outside the main library, make it obvious in the summary. either by prepending a "tag" (though i kind of dislike that, as the redundancy looks a bit silly when browsing only that file's history), or by cleverly working relevant keywords into it.

**Comment by RonaldAJ** [comment]
I have very little time available at present. Please move forward without me.

**Comment by larsimmisch** [comment]
@RonaldAJ 
> I have very little time available at present. Please move forward without me.
Don't worry about it and feel free to just ignore review requests!

**Comment by larsimmisch** [comment]
@ossilator 
> amended the commit.

Thanks. I like the idea of an AUTHORS.md file, but what you did is fine.

Regarding unrelated changes and pushing to main: sorry. I guess I've been alone on my island for too long.

**Pull request merged**
