### PR TITLE
fix generate switch capabilities

### PR DESCRIPTION
**Pull request by stalkerg**
I suppose it was a copy/paste mistake. 
Regards,

### CODE REVIEW

**Comment by larsimmisch** [comment]
Yes, that looks like copypasta, thanks. How did you validate your changes?

**Comment by stalkerg** [comment]
I tried a mute device with mute capability but this library shows me errors like "this device not supported mute". It's actual for many PCM controls. 
After this fixing everything working as expected.

**Comment by stalkerg** [comment]
What can I do else? I really wait for this fix.

**Comment by larsimmisch** [comment]
Looks good, merging.

**Pull request merged**
